fix

diff --git a/templates/elasticsearch.j2 b/templates/elasticsearch.j2
--- a/templates/elasticsearch.j2
+++ b/templates/elasticsearch.j2
@@ -56,16 +56,8 @@ if [ -f "$ES_ENV_FILE" ]; then
     . "$ES_ENV_FILE"
 fi
 
-# ES_USER and ES_GROUP settings were removed
-if [ ! -z "$ES_USER" ] || [ ! -z "$ES_GROUP" ]; then
-# ES_USER and ES_GROUP settings were removed
-if [ ! -z "$ES_USER" ] || [ ! -z "$ES_GROUP" ]; then
-# ES_USER and ES_GROUP settings were removed
-if [ ! -z "$ES_USER" ] || [ ! -z "$ES_GROUP" ]; then
-# ES_USER and ES_GROUP settings were removed
-if [ ! -z "$ES_USER" ] || [ ! -z "$ES_GROUP" ]; then
-    echo "ES_USER and ES_GROUP settings are no longer supported. To run as a custom user/group use the archive distribution of Elasticsearch."
-    exit 1
+if [ "$ES_USER" != "elasticsearch" ] || [ "$ES_GROUP" != "elasticsearch" ]; then
+    echo "WARNING: ES_USER and ES_GROUP are deprecated and will be removed in the next major version of Elasticsearch, got: [$ES_USER:$ES_GROUP]"
 fi
 
 # CONF_FILE setting was removed
@@ -97,8 +89,28 @@ if test -n "$ES_GC_LOG_FILE"; then export ES_GC_LOG_FILE; fi
 
 lockfile=/var/lock/subsys/$prog
 
-    fi
+# backwards compatibility for old config sysconfig files, pre 0.90.1
+if [ -n $USER ] && [ -z $ES_USER ] ; then
+   ES_USER=$USER
+fi
+
+if [ ! -x "$exec" ]; then
+    echo "The elasticsearch startup script does not exists or it is not executable, tried: $exec"
+    exit 1
+fi
+
+checkJava() {
+    if [ -x "$JAVA_HOME/bin/java" ]; then
+        JAVA="$JAVA_HOME/bin/java"
+    else
         JAVA=`which java`
+    fi
+
+    if [ ! -x "$JAVA" ]; then
+        echo "Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME"
+        exit 1
+    fi
+}
 
 start() {
     checkJava
@@ -137,17 +149,29 @@ start() {
     echo
     [ $retval -eq 0 ] && touch $lockfile
     return $retval
-    daemon --user elasticsearch --pidfile $pidfile $exec -p $pidfile -d
+}
+
+stop() {
+    echo -n $"Stopping $prog: "
+    # stop it here, often "killproc $prog"
     killproc -p $pidfile -d 86400 $prog
     retval=$?
     echo
     [ $retval -eq 0 ] && rm -f $lockfile
-    daemon --user elasticsearch --pidfile $pidfile $exec -p $pidfile -d
+    return $retval
+}
+
+restart() {
+    stop
     start
 }
 
 reload() {
-    daemon --user elasticsearch --pidfile $pidfile $exec -p $pidfile -d
+    restart
+}
+
+force_reload() {
+    restart
 }
 
 rh_status() {
